package com.wix.pay.mercurypay.model

case class CaptureResponse(ResponseOrigin: Option[String] = None,
                           DSIXReturnCode: Option[String] = None,
                           CmdStatus: Option[String] = None,
                           TextResponse: Option[String] = None,
                           UserTraceData: Option[String] = None,
                           MerchantID: Option[String] = None,
                           AcctNo: Option[String] = None,
                           ExpDate: Option[String] = None,
                           CardType: Option[String] = None,
                           TranCode: Option[String] = None,
                           AuthCode: Option[String] = None,
                           CaptureStatus: Option[String] = None,
                           RefNo: Option[String] = None,
                           InvoiceNo: Option[String] = None,
                           Purchase: Option[String] = None,
                           Authorize: Option[String] = None,
                           AcqRefData: Option[String] = None,
                           ProcessData: Option[String] = None) extends Response